### ISSUE TITLE
Download is not working on MS Edge

### ISSUE THREAD

**Issue by lukkiddd** [monospaced/angular-qrcode#66]

**Comment by monospaced** [comment]
This is due to lack of support in IE/Edge for data uri hrefs:

https://caniuse.com/#feat=datauri

If you really need this functionality, I would suggest forking and adding some way to force `canvas2D` to be `false` for IE/Edge. This will render an `img` (instead of `canvas`) to the page, which could then be downloaded with context menu, etc.
