### ISSUE TITLE
How to print on a device

### ISSUE THREAD

**Issue by Ross-Rawlins** [monospaced/angular-qrcode#68]
I am trying to print the qr code in the HTML I pass to a print plugin. But the QR code is not showing. How can I create a temp file to pass the path of to the printer? Or even better yet how can I get the DATA URI that is generated and use it in my component.

**Comment by excitepv** [comment]
@Ross-Rawlins This is due to rendering canvas in print window.
As a workaround, I have disabled canvas and used image by **adding the below code in angular-qrcode.js after line number 39**
`canvas2D = (print in attrs)? false :true;`
**Then in the directive add this**
`<qrcode data="string" print></qrcode>`
