### ISSUE TITLE
Printing issues

### ISSUE THREAD

**Issue by kimsean** [monospaced/angular-qrcode#71]
Hi. how to print the rendered barcodes ? i use the module ngPrint. but it doesn't render on the preview.

**Comment by excitepv** [comment]
@kimsean This is due to rendering canvas in print window.
As a workaround, I have disabled canvas and used image by **adding the below code in angular-qrcode.js after line number 39**
`canvas2D = (print in attrs)? false :true;`
**Then in the directive add this**
`<qrcode data="string" print></qrcode>`
